### PR TITLE
Run flake8 on CI

### PR DESCRIPTION
**Pull request by nre-ableton**
- Add flake8 to Python requirements
- Add docstrings to tests
- Arrange imports correctly
- Run flake8 on CI

### CODE REVIEW

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Comment by ala-ableton** [comment]
@nre-ableton FYI, I pushed a fixup commit to improve the isort configuration

**Comment by nre-ableton** [comment]
@ablbot autosqaush

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Review by mst-ableton — APPROVED** [review]
lgtm, nice!

**Pull request merged**
