### PR TITLE
Lint Molecule files with ansible-lint

### PR DESCRIPTION
**Pull request by nre-ableton**
Also includes a few other minor cleanups to dotfiles

### CODE REVIEW

**Comment by nre-ableton** [comment]
@ablbot rebase

**Review by rco-ableton — APPROVED** [review]

**Comment by nre-ableton** [comment]
I had to add 615e723, mind taking another look @rco-ableton ?

**Review by rco-ableton — APPROVED** [review]

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Comment by nre-ableton** [comment]
@ablbot rebase

**Pull request merged**
